### ISSUE TITLE
rejected_r_values 

### ISSUE THREAD

**Issue by simonzcaiman** [iisayoo/johansen#4]
Hi dear,

Thanks for these awesome scripts. One question I have is that when johansen() returns eigenvectors and rejected_r_values, if r=x null hypothesis got rejected, should we append x+1 into the rejected_r_values list? 
My idea is that if we rejected the null hypothesis r=0 , we should have 1 (using maxeigen) or 3(using trace) cointegrating vectors, therefore we should append r=1 into the rejected_r_values list. 
For example,
        rejected_r_values = []
        for r in range(m):
            if self.h_test(eigenvalues, r):
                rejected_r_values.append(r+1)

In your notebook example, where the johansen function returns r=[1], I don't quite understand how you get r=[1] only. Because in the johansen function, rejected_r_values should be like [0,1]. Could you elaborate more on this? Thank you so much! 

Once again, thanks for the awesome work!

**Comment by simonzcaiman** [comment]
Oh. I think I got the rejected_r_values part. If we can reject r=0, then we will append 0 to that list. 
However, I still do not sure about the example in your notebook. Should we print out [0,1] instead of [1] with this line of code 
print "r values are: {}".format(r)

Thank you!

**Comment by iisayoo** [comment]
Hi there, thank you for the kind words. I'm glad you are finding the code useful.

In the example r=0 is not included because the null hypothesis H0 is not rejected for r=0 in the hypothesis test, i.e. for r=0 the trace statistic is not larger than the critical value. It is possible for H0 to be rejected for some value of r, but not rejected for a lower value. 

Hope this helps.
